apiVersion: v1
kind: Service
metadata:
  name: hey
  labels:
    app: hey
    service: hey
spec:
  selector:
    app: hey
    service: hey
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP